Fix ERROR M310 when directory name starts with .
Open-CMSIS-Pack/devtools pull request #137
Opened 2022-02-16 15:57 UTC by jeromecoutant

Fix #110 

See https://github.com/Open-CMSIS-Pack/devtools/issues/110#issuecomment-1033913423

@thorstendb-ARM

2022-02-17 08:23 UTC, jeromecoutant commented
> Merging [#137] will **decrease** coverage by `13.87%`.

I think there is an issue in Codecov tool....

2022-02-17 09:16 UTC, thorstendb-ARM submitted a review, later dismissed

2022-02-22 09:05 UTC, JonatanAntoni commented
> I think there is an issue in Codecov tool....
Yes, the CodeCoverage seems to be not properly configured. We need to check.

Can we add some tests to?
 * Reproduce the original issue.
 * Verify the fix does the job.

2022-02-25 17:09 UTC, jeromecoutant commented
> Can we add some tests for this function?

I think it's done :-)
 
>     Reproduce the original issue.

With only the commit with the new test:
```
$ cmake --build . --target packchk --target PackChkIntegTests

$ ctest -C Debug -R PackChkIntegTests

Test project C:/github/OpenCMSISPack/devtools/build
    Start 13: PackChkIntegTests
1/1 Test #13: PackChkIntegTests ................***Failed    1.27 sec

[  FAILED  ] PackChkIntegTests.CheckPackWithDot (7 ms)
```

>     Verify the fix does the job.

With the patch:
```
$ cmake --build . --target packchk --target PackChkIntegTests

$ ctest -C Debug -R PackChkIntegTests
1/1 Test #13: PackChkIntegTests ................   Passed    1.45 sec
```

2022-02-28 10:35 UTC, JonatanAntoni commented
Looks promising. I think we could add a unit test in addition to the integration test.

2022-02-28 11:13 UTC, JonatanAntoni requested changes
The coverage reports turns out that the code range under discussion is not properly hit by the provided tests.

2022-02-28 11:13 UTC, JonatanAntoni commented on tools/packchk/test/data/TestPackDot/TestVendor.TestPackDot.pdsc
> +        <file category="source" name=".Files/test1.c"/>
What are we trying to test here? Filenames starting with a `.` should be legal. At least on unix-like systems such files/directories are considered "hidden".
Didn't we discuss (and test) for names starting with `./`? I.e., the unix-like shortcut for "current working directory"?

2022-02-28 13:45 UTC, JonatanAntoni commented on tools/packchk/test/data/TestPackDot/TestVendor.TestPackDot.pdsc
> +        <file category="source" name=".Files/test1.c"/>
Okay, so this test actually does not verify the removal of `./` prefixes, intentionally. So we definitively need to add some more tests, probably unit tests, to really cover the implementation.

2022-03-08 14:16 UTC, jeromecoutant commented
> So we definitively need to add some more tests, probably unit tests, to really cover the implementation

Any update ?
Thx

2022-03-22 10:29 UTC, fred-r commented
What can we do about the codecov issue blocking the merge ?

2022-03-25 15:55 UTC, jeromecoutant commented
@JonatanAntoni any update ?
Thx

2022-03-28 12:07 UTC, JonatanAntoni commented
@jeromecoutant,

We need to provide more tests to be sure the function does what is expected.
Please rebase your patch and add some tests which cover the code under modification.

Cheers,
Jonatan

2022-03-28 12:14 UTC, jeromecoutant commented
> Please rebase your patch and add some tests which cover the code under modification.

Done

2022-04-05 14:55 UTC, JonatanAntoni commented
@jeromecoutant, after merging #262 please consider rebasing this PR to keep contributing your integration test. Actually, we should already have everything covered with the unit tests but the additional integ test would not harm.

2022-04-20 07:57 UTC, jeromecoutant commented
@JonatanAntoni ?

2022-04-20 08:13 UTC, JonatanAntoni approved these changes

2022-04-20 08:40 UTC, merged