[packchk] Add xml validation for input PDSCs (#506)
Open-CMSIS-Pack/devtools pull request #736
Opened 2023-02-13 06:15 UTC by yvesll

Signed-off-by: yvesll <toyears@hotmail.com>

2023-02-13 13:24 UTC, JonatanAntoni commented
Thanks @yvesll for your contribution. Unfortunately, I see some challenged with this enhancement. 

First of all, I'd like to understand why you think the schema check should be integrated into PackChk, natively.

I added an explicit schema check into the gen-pack script library, see https://github.com/Open-CMSIS-Pack/gen-pack/blob/27feb09121b49fdc7bf95e6927df9a50454cdffb/gen-pack#L80-L121. This uses xmllint from libxml2 which is available under MIT license for all supported platforms.

If you still think the schema check should be integral part of packchk, we'd need to sort out open questions. The PR currently fails the checks. This could be due to linking Xerces library dynamically but not shipping the required library alongside the binary. So far, we link everything statically and accept larger binaries to prevent shared lib issues across different platforms and versions.

Cheers,
Jonatan

2023-02-13 14:05 UTC, yvesll commented
HI, @JonatanAntoni, thanks for the comments.
For the failed checks, I am still exploring an elegant way to dynamically link the Xerces-c library and make sure it can work for all supported arches. Building the static lib may evidently increase the binary size but I appreciate it if we accept it.

For the motivation of this PR, you can see discussions in #506.

2023-02-13 14:43 UTC, JonatanAntoni commented
@yvesll, thanks for clarifying this. I think we should accept the static linkage overhead as we want our CMSIS-Toolbox to be independent from a specific Linux distro. Perhaps changing the build to use static link would already solve the remaining issue.

2023-02-14 08:25 UTC, edriouk requested changes

2023-02-14 08:25 UTC, edriouk commented on tools/packchk/include/CreateModel.h
> +#include "XmlValidator.h"
XmlValidator includes Xerces includes, they should not poison the code.

2023-02-14 08:25 UTC, edriouk commented on tools/packchk/include/CreateModel.h
> +  XmlValidator m_xmlValidator;
Making this a dynamically allocated pointer would solve two problems:
1) no need to include XmlValidator.h in the header, forward declaration is sufficient.
2) the object can be created only if needed (validation is enabled)

2023-02-14 08:25 UTC, edriouk commented on libs/xmlschemachecker/test/data/PACK.xsd
> +<?xml version="1.0" encoding="UTF-8"?>
Could we pull this file from its original location?
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/tree/main/schema

2023-02-14 08:25 UTC, edriouk commented on libs/xmlschemachecker/CMakeLists.txt
> +        SYSTEM ${CMAKE_BINARY_DIR}/external/xerces-c
all xerces includes should be made private and not exposed to outside the library.

2023-02-17 09:01 UTC, yvesll commented
Can someone help me rerun the "CodeQL" check? I do not have access and it seems a network issue.

2023-02-28 04:20 UTC, yvesll commented
@thorstendb-ARM, sorry, I click the re-request button but not sure why it removes you from the list, can you join the review again?

2023-02-28 06:46 UTC, edriouk approved these changes
Looks good.
@JonatanAntoni, could we disable static analysis for all external modules?

2023-02-28 16:22 UTC, edriouk commented
Code QL issues are ignored because they mostly come from an external  module Xerces

2023-02-28 16:22 UTC, merged

2023-05-23 09:35 UTC, thorstendb-ARM commented
@yvesll , why did you add this? I am trying to find out which is better, stopping after the first found error vs. reporting all errors including subsequent ones.
`m_domParser->setValidationConstraintFatal(true);`

2023-05-29 06:16 UTC, yvesll commented
@thorstendb-ARM, this field was set to test **setExitOnFirstFatalError** in the development stage and I forgot to remove it. I think both of the two ways make sense in different use cases, so an extra option is better.